### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mintupgrade#1]
Checks before repo switch
-----------------------------------
- [x] Check if repositories are up to date
- [x] Check if repositories support target
- [x] Check policy
- [x] Check foreign packages from a Mint point of view

Checks during simulation
---------------------------------
- [x] Check conflicts/error in simulation
- [x] Check removals in simulation
- [x] Check download size and free space on HDD
- [x] Check foreign packages from a target point of view

Checks after upgrade
-----------------------------
- [x] Conflicts
- [x] Downgrades
- [x] meta

**Comment by ghost** [comment]
Out of curiosity:
**1.** What happens to the system files that have been modified/patched by the user? Is there any check for their size/creation date/version/etc? Suppose the user has fixed a particular issue pertaining to their machine in, say, some Python script belonging to Cinnamon or other system component, and that fix is not in the new release - would it sound reasonable to have that modified file backed up and a special mention about it added somewhere in a log or better yet in a GUI summary?
**2.** What about other user-specific settings such as no password requirement whatsoever, current theme+icon set, panel mode (Modern or Classic), installed/enabled Spices (in Cinnamon), and any other possible customizations more or less visible - are they checked for and user notified about the requirement to change/disable/uninstall/update/etc prior to any change happening, that is prior to starting the actual upgrade?
**3.** Is there any option to specify an alternative download location for the upgrade packages in case the root partition/drive doesn't have enough space for both those packages and the unpacked/temporary files?
**4.** Is there an option to upgrade from a DVD image (.iso) as is or one burned to disc or USB stick, as opposed to online upgrade?

As mentioned, these questions are only out of curiosity since personally I can't upgrade my 19.2 Cinnamon for a variety of reasons, both hardware-related and personal. Just hoping to help others by bringing into attention certain (niche?) issues that other people might care about too.

**Comment by clefebvre** [comment]
1. APT is told to overwrite using the new version of the files. That results in old versions being backed up though, in the same directory.
2. Nothing is changed when it comes to user configuration. Your configuration is kept.
3. New in this tool is the calculation of download/required space and the check for free space. You're asked to free space if you don't have enough. There is no mechanism in place to use alternative locations though.
4. No.
